# -*- coding: utf-8 -*-
"""EjericiciosProcesosEstocasticos.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1UnIaRpxJIyMrDO3JAxvTrr3zf7k6Kbon
"""

import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

# Configuración de estilo profesional
sns.set_theme(style="whitegrid", context="notebook")
colores_fes = ['#2C4B78', '#B8862D', '#5A6B7C'] # Azul, Dorado, Gris

def simular_cadena_embebida(T, alpha, beta, gamma, delta):
    # Tasas totales de salida para cada estado
    tasas = np.array([alpha, beta + gamma, delta])

    # Matriz de transición de la cadena embebida P(x,y)
    P = np.array([
        [0.0, 1.0, 0.0],
        [beta/(beta+gamma), 0.0, gamma/(beta+gamma)],
        [1.0, 0.0, 0.0]
    ])

    t, estado = 0.0, 0
    tiempos, estados = [0.0], [0]
    tiempo_ocupacion = np.zeros(3)

    while t < T:
        tasa_actual = tasas[estado]
        # Generar tiempo de permanencia exponencial
        sojourn = np.random.exponential(1.0 / tasa_actual)

        # Si el salto ocurre después del horizonte T, truncamos
        if t + sojourn > T:
            tiempo_ocupacion[estado] += (T - t)
            tiempos.append(T)
            estados.append(estado)
            break

        tiempo_ocupacion[estado] += sojourn
        t += sojourn

        # Saltar al siguiente estado usando la cadena embebida
        siguiente_estado = np.random.choice([0, 1, 2], p=P[estado])

        tiempos.append(t)
        estados.append(estado)
        estado = siguiente_estado

    proporciones = tiempo_ocupacion / T
    return tiempos, estados, proporciones

# Parámetros de prueba
a, b, c, d = 1.0, 2.0, 1.5, 0.5
T_sim = 10000

# Simulación
tiempos, estados, prop_empiricas = simular_cadena_embebida(T_sim, a, b, c, d)

# Cálculo Teórico (Resolviendo pi * A = 0)
denom = b*c + a*c + a*b
pi_teorica = np.array([(b*c)/denom, (a*c)/denom, (a*b)/denom])

print("--- RESULTADOS EJERCICIO 1.11 ---")
print(f"Horizonte (T): {T_sim}")
print(f"Proporciones Teóricas: {pi_teorica}")
print(f"Proporciones Empíricas: {prop_empiricas}")

# ----- GENERACIÓN DE LA GRÁFICA -----
fig, (ax1, ax2) = plt.subplots(1, 2, figsize=(14, 5), gridspec_kw={'width_ratios': [2, 1]})

# Panel izquierdo: Trayectoria
ax1.step(tiempos[:80], estados[:80], where='post', color=colores_fes[0], linewidth=2)
ax1.fill_between(tiempos[:80], estados[:80], step="post", alpha=0.1, color=colores_fes[0])
ax1.set_yticks([0, 1, 2])
ax1.set_title('Trayectoria de la Cadena a Tiempo Continuo', fontsize=14, fontweight='bold')
ax1.set_xlabel('Tiempo (t)', fontsize=12)
ax1.set_ylabel('Estado', fontsize=12)

# Panel derecho: Comparativa de ocupación
x_labels = ['Estado 0', 'Estado 1', 'Estado 2']
x = np.arange(len(x_labels))
width = 0.35

ax2.bar(x - width/2, pi_teorica, width, label='Teórica ($\pi$)', color=colores_fes[1])
ax2.bar(x + width/2, prop_empiricas, width, label='Empírica', color=colores_fes[2])
ax2.set_title('Proporción de Ocupación vs Equilibrio', fontsize=14, fontweight='bold')
ax2.set_xticks(x)
ax2.set_xticklabels(x_labels)
ax2.legend()

plt.tight_layout()
plt.savefig('fig1_11_pro.png', dpi=300)
plt.show()

import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

# Configuración de estilo profesional
sns.set_theme(style="whitegrid", context="notebook")

def simular_nacimiento_muerte(T, lam, mu):
    t, estado = 0.0, 0
    tiempos, estados = [0.0], [0]
    area_integral = 0.0

    while t < T:
        # Tasa total de salida: lambda (siempre) + mu (solo si hay clientes)
        tasa_muerte = mu if estado > 0 else 0.0
        tasa_total = lam + tasa_muerte

        # Tiempo de permanencia
        sojourn = np.random.exponential(1.0 / tasa_total)

        # Truncamiento al final del horizonte temporal
        if t + sojourn > T:
            area_integral += estado * (T - t)
            tiempos.append(T)
            estados.append(estado)
            break

        area_integral += estado * sojourn
        t += sojourn

        # Decidir si es nacimiento o muerte
        prob_nacimiento = lam / tasa_total
        if np.random.rand() < prob_nacimiento:
            estado += 1
        else:
            estado -= 1

        tiempos.append(t)
        estados.append(estado)

    media_empirica = area_integral / T
    return tiempos, estados, media_empirica

T_nm = 500
# Simulamos los 3 regímenes
t_sub, e_sub, media_sub = simular_nacimiento_muerte(T_nm, lam=1.0, mu=2.0)
t_crit, e_crit, _ = simular_nacimiento_muerte(T_nm, lam=2.0, mu=2.0)
t_sup, e_sup, _ = simular_nacimiento_muerte(T_nm, lam=2.0, mu=1.0)

# Cálculos teóricos para el subcrítico
rho = 1.0 / 2.0
media_teorica = rho / (1.0 - rho)

print("--- RESULTADOS EJERCICIO 1.12 ---")
print(f"Horizonte (T): {T_nm}")
print(f"Régimen Subcrítico (lam=1, mu=2):")
print(f"  -> Media Teórica Estacionaria: {media_teorica:.4f}")
print(f"  -> Media Empírica Temporal:    {media_sub:.4f}")

# ----- GENERACIÓN DE LA GRÁFICA -----
fig, axes = plt.subplots(3, 1, figsize=(12, 10), sharex=True)
fig.suptitle('Comportamiento Transiente de la Cadena Nacimiento-Muerte', fontsize=16, fontweight='bold', y=0.98)

# Panel 1: Subcrítico
axes[0].step(t_sub, e_sub, where='post', color='seagreen', linewidth=1.5)
axes[0].fill_between(t_sub, e_sub, step="post", alpha=0.2, color='seagreen')
axes[0].set_title(r'Régimen Subcrítico ($\lambda = 1 < \mu = 2$): Recurrente Positivo', fontsize=13)
axes[0].set_ylabel('Clientes ($X_t$)', fontsize=11)

# Panel 2: Crítico
axes[1].step(t_crit, e_crit, where='post', color='goldenrod', linewidth=1.5)
axes[1].fill_between(t_crit, e_crit, step="post", alpha=0.2, color='goldenrod')
axes[1].set_title(r'Régimen Crítico ($\lambda = 2 = \mu = 2$): Nulo-Recurrente', fontsize=13)
axes[1].set_ylabel('Clientes ($X_t$)', fontsize=11)

# Panel 3: Supercrítico
axes[2].step(t_sup, e_sup, where='post', color='indianred', linewidth=1.5)
axes[2].fill_between(t_sup, e_sup, step="post", alpha=0.2, color='indianred')
axes[2].set_title(r'Régimen Supercrítico ($\lambda = 2 > \mu = 1$): Transitorio (Explosivo)', fontsize=13)
axes[2].set_ylabel('Clientes ($X_t$)', fontsize=11)
axes[2].set_xlabel('Tiempo (t)', fontsize=12)

plt.tight_layout()
plt.savefig('fig1_12_pro.png', dpi=300)
plt.show()

import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from scipy.stats import gamma

# Configuración de estilo profesional
sns.set_theme(style="whitegrid", context="notebook")
colores_fes = ['#2C4B78', '#B8862D', '#5A6B7C'] # Azul, Dorado, Gris

def simular_tiempos_poisson(n, lam, num_simulaciones):
    # Generar matriz de (num_simulaciones x n) variables exponenciales
    exponenciales = np.random.exponential(1.0 / lam, (num_simulaciones, n))
    # El tiempo Tn del n-ésimo salto es la suma de los n tiempos inter-arribo
    Tn = np.sum(exponenciales, axis=1)
    return Tn

# Parámetros del ejercicio
n_val = 5
lam_val = 2.0
num_sims = 10000

# Ejecutar simulación
Tn_simulados = simular_tiempos_poisson(n_val, lam_val, num_sims)

# Cálculos numéricos y teóricos
media_empirica = np.mean(Tn_simulados)
var_empirica = np.var(Tn_simulados)

media_teorica = n_val / lam_val
var_teorica = n_val / (lam_val**2)

print("--- RESULTADOS EJERCICIO 2.11 ---")
print(f"Parámetros: n = {n_val}, lambda = {lam_val}")
print(f"Media Empírica:   {media_empirica:.4f}  |  Media Teórica:   {media_teorica:.4f}")
print(f"Varianza Empírica: {var_empirica:.4f}  |  Varianza Teórica: {var_teorica:.4f}")

# ----- GENERACIÓN DE LA GRÁFICA -----
plt.figure(figsize=(10, 6))

# Histograma empírico y KDE (Kernel Density Estimation)
sns.histplot(Tn_simulados, bins=40, stat='density', color=colores_fes[0], alpha=0.5, label='Frecuencia Empírica (Monte Carlo)')
sns.kdeplot(Tn_simulados, color=colores_fes[2], lw=2, linestyle='--', label='KDE (Suavizado Empírico)')

# Curva Teórica de la distribución Gamma
x = np.linspace(0, max(Tn_simulados), 200)
# En scipy.stats.gamma, 'a' es el parámetro de forma (n) y 'scale' es 1/lambda
plt.plot(x, gamma.pdf(x, a=n_val, scale=1.0/lam_val), color=colores_fes[1], lw=2.5, label=f'PDF Teórica Gamma(n={n_val}, $\lambda$={lam_val})')

plt.title(f'Distribución del Tiempo hasta el {n_val}º Salto ($T_{{{n_val}}}$)', fontsize=15, fontweight='bold')
plt.xlabel('Tiempo (t)', fontsize=12)
plt.ylabel('Densidad de Probabilidad', fontsize=12)
plt.legend(fontsize=11)

plt.tight_layout()
plt.savefig('fig2_11_pro.png', dpi=300)
plt.show()

import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from scipy.stats import poisson

# Configuración de estilo profesional
sns.set_theme(style="whitegrid", context="notebook")
colores_fes = ['#2C4B78', '#B8862D', '#5A6B7C']

# Parámetros generales
T_val = 10.0
num_sims = 10000

# ==========================================
# PARTE 1: ADELGAZAMIENTO (THINNING)
# ==========================================
lam_base = 5.0
p_marca = 0.3

# Simulamos el número total de eventos en T para 10,000 trayectorias
N_T = np.random.poisson(lam_base * T_val, num_sims)

# Cada evento total tiene probabilidad p_marca de ser "marcado" (Binomial)
N_1 = np.random.binomial(N_T, p_marca)
N_0 = N_T - N_1  # Eventos no marcados

# Verificación de covarianza para probar independencia empírica
cov_empirica = np.cov(N_1, N_0)[0, 1]

# ==========================================
# PARTE 2: SUPERPOSICIÓN
# ==========================================
lam_1 = 3.0
lam_2 = 4.0

# Simulamos conteos de dos procesos independientes
N1_indep = np.random.poisson(lam_1 * T_val, num_sims)
N2_indep = np.random.poisson(lam_2 * T_val, num_sims)

# Súmamos los eventos
N_suma = N1_indep + N2_indep

print("--- RESULTADOS EJERCICIO 2.12 ---")
print(">> ADELGAZAMIENTO:")
print(f"Media N_1 (Marcados) Empírica: {np.mean(N_1):.4f}  |  Teórica (lam*p*T): {lam_base*p_marca*T_val:.4f}")
print(f"Covarianza empírica (N_1, N_0): {cov_empirica:.4f} (Teóricamente debe ser 0)")
print("\n>> SUPERPOSICIÓN:")
print(f"Media Suma Empírica: {np.mean(N_suma):.4f}  |  Teórica (lam1+lam2)*T: {(lam_1+lam_2)*T_val:.4f}")

# ----- GENERACIÓN DE LA GRÁFICA -----
fig, (ax1, ax2) = plt.subplots(1, 2, figsize=(15, 6))

# Panel 1: Adelgazamiento (Frecuencias)
val_1, counts_1 = np.unique(N_1, return_counts=True)
ax1.bar(val_1, counts_1/num_sims, color=colores_fes[0], alpha=0.7, label='$N^{(1)}$ (Marcados)')
ax1.plot(val_1, poisson.pmf(val_1, lam_base*p_marca*T_val), 'ko--', lw=1.5, label=f'Teórica Poisson($\lambda p T = {lam_base*p_marca*T_val}$)')
ax1.set_title('Adelgazamiento (Thinning)', fontsize=14, fontweight='bold')
ax1.set_xlabel('Número de Eventos', fontsize=12)
ax1.set_ylabel('Frecuencia Relativa', fontsize=12)
ax1.legend()

# Panel 2: Superposición
val_suma, counts_suma = np.unique(N_suma, return_counts=True)
ax2.bar(val_suma, counts_suma/num_sims, color=colores_fes[1], alpha=0.7, label='$N^{(1)} + N^{(2)}$ (Suma empírica)')
ax2.plot(val_suma, poisson.pmf(val_suma, (lam_1+lam_2)*T_val), 'ro--', lw=1.5, label=f'Teórica Poisson($(\lambda_1+\lambda_2)T = {(lam_1+lam_2)*T_val}$)')
ax2.set_title('Superposición de Procesos Independientes', fontsize=14, fontweight='bold')
ax2.set_xlabel('Número Total de Eventos', fontsize=12)
ax2.legend()

plt.tight_layout()
plt.savefig('fig2_12_pro.png', dpi=300)
plt.show()

import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import heapq
import math

# Configuración de estilo profesional
sns.set_theme(style="whitegrid", context="notebook")
colores_fes = ['#2C4B78', '#B8862D', '#5A6B7C']

def simular_mmk_eventos(lam, mu, k, T_max):
    t = 0.0
    # Cola de prioridad para agendar eventos: (tiempo_evento, tipo_evento)
    eventos = []
    heapq.heappush(eventos, (np.random.exponential(1.0/lam), 'llegada'))

    servidores_libres = k
    cola_espera = []      # Guarda el tiempo de llegada de quienes están en fila
    tiempos_espera = []   # Guarda el tiempo total C de espera de cada cliente

    # Variables para graficar la trayectoria del sistema
    tiempos_plot = [0.0]
    clientes_sistema = [0]
    n_clientes = 0

    while eventos and t < T_max:
        t, tipo = heapq.heappop(eventos)

        if tipo == 'llegada':
            n_clientes += 1
            tiempos_plot.append(t)
            clientes_sistema.append(n_clientes)

            # Programar la PRÓXIMA llegada
            heapq.heappush(eventos, (t + np.random.exponential(1.0/lam), 'llegada'))

            if servidores_libres > 0:
                # Pasa directo al servidor
                servidores_libres -= 1
                tiempos_espera.append(0.0) # No esperó nada
                # Programar su salida
                heapq.heappush(eventos, (t + np.random.exponential(1.0/mu), 'salida'))
            else:
                # No hay servidores, se forma en la fila
                cola_espera.append(t)

        elif tipo == 'salida':
            n_clientes -= 1
            tiempos_plot.append(t)
            clientes_sistema.append(n_clientes)

            if len(cola_espera) > 0:
                # Hay gente en la fila, pasa el primero
                t_llegada = cola_espera.pop(0)
                tiempos_espera.append(t - t_llegada) # Calculamos cuánto esperó
                # Programar su salida
                heapq.heappush(eventos, (t + np.random.exponential(1.0/mu), 'salida'))
            else:
                # Nadie en la fila, se libera un servidor
                servidores_libres += 1

    return np.array(tiempos_espera), tiempos_plot, clientes_sistema

# Parámetros: lam=8, mu=2, k=5 => rho = 8/10 = 0.8 (Tráfico pesado)
lam_k, mu_k, k_serv = 8.0, 2.0, 5
T_sim_k = 10000

# Correr simulación
esperas, t_plot, n_plot = simular_mmk_eventos(lam_k, mu_k, k_serv, T_sim_k)

# Descartamos el primer 10% de los datos como periodo de "calentamiento"
esperas_estacionarias = esperas[int(len(esperas)*0.1):]

P_C_mayor_0_emp = np.mean(esperas_estacionarias > 0)
E_C_emp = np.mean(esperas_estacionarias)

# Cálculos Teóricos (Erlang C)
rho = lam_k / (k_serv * mu_k)
sum_term = sum([(k_serv * rho)**n / math.factorial(n) for n in range(k_serv)])
erlang_c_num = ((k_serv * rho)**k_serv / (math.factorial(k_serv) * (1 - rho)))
Erlang_C = erlang_c_num / (sum_term + erlang_c_num)
E_C_teo = Erlang_C / (k_serv * mu_k - lam_k)

print("--- RESULTADOS EJERCICIO 3.11 ---")
print(f"Probabilidad de hacer fila P(C > 0):")
print(f"  > Empírica: {P_C_mayor_0_emp:.4f}  |  Teórica (Erlang C): {Erlang_C:.4f}")
print(f"Tiempo esperado en fila E[C]:")
print(f"  > Empírica: {E_C_emp:.4f}  |  Teórica (Little):   {E_C_teo:.4f}")

# ----- GENERACIÓN DE LA GRÁFICA -----
fig, (ax1, ax2) = plt.subplots(1, 2, figsize=(15, 5))

# Panel 1: Trayectoria (Primeros eventos)
limit = 200 # Graficar solo una ventana corta para que se aprecie
ax1.step(t_plot[:limit], n_plot[:limit], where='post', color=colores_fes[0], lw=2)
ax1.fill_between(t_plot[:limit], n_plot[:limit], step='post', alpha=0.15, color=colores_fes[0])
ax1.axhline(k_serv, color='red', linestyle='--', lw=2, label=f'Capacidad Instalada ($k={k_serv}$)')
ax1.set_title('Trayectoria Dinámica M/M/k', fontsize=14, fontweight='bold')
ax1.set_xlabel('Tiempo (t)', fontsize=12)
ax1.set_ylabel('Clientes en el sistema ($X_t$)', fontsize=12)
ax1.legend()

# Panel 2: Histograma de Tiempos de Espera
esperas_positivas = esperas_estacionarias[esperas_estacionarias > 0]
sns.histplot(esperas_positivas, bins=40, stat='density', color=colores_fes[1], alpha=0.7, ax=ax2)
ax2.axvline(E_C_emp, color='k', linestyle='dashed', linewidth=2.5, label=f'$\mathbb{{E}}[C]$ Empírica: {E_C_emp:.3f}')
ax2.set_title('Distribución Condicional de Esperas ($C > 0$)', fontsize=14, fontweight='bold')
ax2.set_xlabel('Tiempo de Espera en Fila ($C$)', fontsize=12)
ax2.set_ylabel('Densidad de Probabilidad', fontsize=12)
ax2.legend()

plt.tight_layout()
plt.savefig('fig3_11_pro.png', dpi=300)
plt.show()

import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

# Configuración de estilo profesional para la gráfica
sns.set_theme(style="whitegrid", context="notebook")
colores_fes = ['#2C4B78', '#B8862D', '#5A6B7C'] # Azul, Dorado, Gris

def trayectorias_mm_inf(x_0, lam, mu, T_max, n_paths, num_puntos=50):
    """
    Simula múltiples trayectorias de una cola M/M/infinito y
    las interpola en una malla de tiempo fija para calcular momentos.
    """
    t_grid = np.linspace(0, T_max, num_puntos)
    paths = np.zeros((n_paths, num_puntos))
    paths[:, 0] = x_0

    for i in range(n_paths):
        t, estado = 0.0, x_0
        idx = 1
        while idx < num_puntos:
            # En M/M/inf, la tasa de salida depende del número de clientes en el sistema
            tasa_salida = estado * mu
            tasa_total = lam + tasa_salida

            # Tiempo hasta el próximo evento
            sojourn = np.random.exponential(1.0 / tasa_total)

            # Registrar el estado en la malla de tiempo
            while idx < num_puntos and t_grid[idx] < t + sojourn:
                paths[i, idx] = estado
                idx += 1

            t += sojourn

            # Determinar si el evento fue llegada o salida
            if np.random.rand() < lam / tasa_total:
                estado += 1
            else:
                estado -= 1

    return t_grid, paths

# Parámetros del experimento
x_inicial = 30           # Carga inicial artificialmente alta
lam_inf, mu_inf = 10.0, 1.0  # Equilibrio teórico = lambda / mu = 10
n_trayectorias = 1000    # Número de caminos a simular
T_inf = 5.0              # Horizonte de tiempo

# Ejecutar la simulación
print("Simulando trayectorias... esto puede tomar unos segundos.")
t_grid, matrix_paths = trayectorias_mm_inf(x_inicial, lam_inf, mu_inf, T_inf, n_trayectorias)

# Cálculos Empíricos (promedio y varianza sobre las 1000 trayectorias en cada instante)
medias_empiricas = np.mean(matrix_paths, axis=0)
varianzas_empiricas = np.var(matrix_paths, axis=0)

# Cálculos Teóricos
# E[X_t] = Var(X_t) = x_0 * e^{-mu*t} + (lambda/mu) * (1 - e^{-mu*t})
medias_teoricas = x_inicial * np.exp(-mu_inf * t_grid) + (lam_inf/mu_inf) * (1 - np.exp(-mu_inf * t_grid))

print("--- RESULTADOS EJERCICIO 3.12 ---")
print(f"Límite estacionario esperado (lam/mu): {lam_inf/mu_inf}")
print(f"Media final empírica en T={T_inf}: {medias_empiricas[-1]:.4f}")
print(f"Varianza final empírica en T={T_inf}: {varianzas_empiricas[-1]:.4f}")

# ----- GENERACIÓN DE LA GRÁFICA -----
fig, (ax1, ax2) = plt.subplots(1, 2, figsize=(15, 6))

# Panel 1: Trayectorias y Evolución de la Media
for i in range(15): # Mostramos solo 15 trayectorias de fondo para no saturar
    ax1.plot(t_grid, matrix_paths[i, :], color=colores_fes[2], alpha=0.15)

ax1.plot(t_grid, medias_empiricas, color=colores_fes[0], lw=3, label='Media Empírica $\mathbb{E}[X_t]$')
ax1.plot(t_grid, medias_teoricas, color=colores_fes[1], lw=2, linestyle='--', label='Media Teórica')
ax1.axhline(lam_inf/mu_inf, color='red', linestyle=':', label='Equilibrio Teórico ($\lambda/\mu$)')

ax1.set_title('Relajación del Sistema M/M/$\infty$', fontsize=14, fontweight='bold')
ax1.set_xlabel('Tiempo (t)', fontsize=12)
ax1.set_ylabel('Trabajos Activos ($X_t$)', fontsize=12)
ax1.legend()

# Panel 2: Convergencia de Momentos (Media y Varianza)
ax2.plot(t_grid, medias_empiricas, color=colores_fes[0], lw=2.5, label='Media Empírica')
ax2.plot(t_grid, varianzas_empiricas, color='purple', lw=2.5, label='Varianza Empírica')
ax2.axhline(lam_inf/mu_inf, color='red', linestyle=':', lw=2, label='Límite Estacionario ($\lambda/\mu$)')

ax2.set_title('Convergencia de Momentos (Propiedad Poisson)', fontsize=14, fontweight='bold')
ax2.set_xlabel('Tiempo (t)', fontsize=12)
ax2.set_ylabel('Valor', fontsize=12)
ax2.legend()

plt.tight_layout()
plt.savefig('fig3_12_pro.png', dpi=300)
plt.show()

import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from matplotlib.colors import ListedColormap

# Configuración de estilo profesional
sns.set_theme(style="white", context="notebook")
colores_fes = ['#2C4B78', '#B8862D', '#5A6B7C']

# ==========================================
# EJERCICIO 4.11: Iteración de Bellman
# ==========================================
# Parámetros del modelo
m = 20           # Espacio de estados {0, 1, ..., m}
N = 50           # Horizonte temporal
p = 0.5          # Probabilidad de subir (caminata simétrica)

estados = np.arange(m + 1)

# Función de ganancia (Payoff): Parabólica convexa g(x) = (x - m/2)^2
# Premia estar en los extremos y penaliza estar en el centro.
g = (estados - m/2)**2

# Construcción de la Matriz de Transición P (con reflexión en los bordes)
P = np.zeros((m + 1, m + 1))
P[0, 1] = 1.0           # Reflexión en 0
P[m, m-1] = 1.0         # Reflexión en m
for i in range(1, m):
    P[i, i-1] = 1 - p
    P[i, i+1] = p

# Inicialización de matrices de Valor (V) y Región de Paro (D)
V = np.zeros((N + 1, m + 1))
D = np.zeros((N + 1, m + 1), dtype=bool) # True = Parar, False = Continuar

# Condición final (Horizonte N)
V[N, :] = g
D[N, :] = True # En el último instante, es obligatorio parar

# Recursión de Bellman (Hacia atrás: N-1 down to 0)
for n in range(N - 1, -1, -1):
    # Valor esperado de continuar: E[V_{n+1}(X_{n+1}) | X_n = x]
    valor_continuar = P @ V[n + 1, :]

    # Decisión óptima: max(Parar, Continuar)
    V[n, :] = np.maximum(g, valor_continuar)

    # Registrar la región de paro
    # Se detiene si la ganancia inmediata es >= al valor esperado de continuar
    D[n, :] = (g >= valor_continuar)

print("--- RESULTADOS EJERCICIO 4.11 ---")
print("Iteración de Bellman completada.")
print(f"Valor esperado máximo desde el centro (x=10) a t=0: {V[0, 10]:.4f}")

# ----- GENERACIÓN DE LA GRÁFICA -----
fig, ax = plt.subplots(figsize=(12, 6))

# Crear un mapa de colores personalizado: Continuar (Azul claro), Parar (Dorado)
cmap_custom = ListedColormap(['#E6EBF5', '#B8862D'])

# Graficamos la transpuesta para que el tiempo sea el eje X y los estados el eje Y
sns.heatmap(D.T, cmap=cmap_custom, cbar=False, ax=ax,
            linewidths=0.5, linecolor='white')

# Estética de la gráfica
ax.invert_yaxis() # Para que el estado 0 esté abajo y el 20 arriba
ax.set_title('Evolución de la Región de Paro $D_n$ en el Tiempo', fontsize=15, fontweight='bold')
ax.set_xlabel('Tiempo ($n$)', fontsize=12)
ax.set_ylabel('Estado ($x$)', fontsize=12)

# Añadir leyenda manualmente
import matplotlib.patches as mpatches
continuar_patch = mpatches.Patch(color='#E6EBF5', label='Región de Continuación ($C_n$)')
parar_patch = mpatches.Patch(color='#B8862D', label='Región de Paro ($D_n$)')
ax.legend(handles=[continuar_patch, parar_patch], loc='upper right', bbox_to_anchor=(1.25, 1))

plt.tight_layout()
plt.savefig('fig4_11_pro.png', dpi=300)
plt.show()

import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

# Configuración de estilo profesional
sns.set_theme(style="whitegrid", context="notebook")
colores_fes = ['#2C4B78', '#B8862D', '#5A6B7C']

# ==========================================
# EJERCICIO 4.12: Monte Carlo para Regla de Umbral
# ==========================================
def simular_venta_umbral(i_star, x_0, K, beta, p, m, num_sims, max_steps=500):
    ganancias_descontadas = np.zeros(num_sims)

    for sim in range(num_sims):
        x = x_0
        n = 0

        # Caminata aleatoria hasta cruzar el umbral o alcanzar límite de tiempo
        while x < i_star and n < max_steps:
            if x == 0:
                x = 1
            elif x == m:
                x = m - 1
            else:
                x += 1 if np.random.rand() < p else -1
            n += 1

        # Si cruzó el umbral antes del límite, calculamos la ganancia descontada
        if x >= i_star:
            ganancias_descontadas[sim] = (beta ** n) * (x - K)
        else:
            ganancias_descontadas[sim] = 0.0 # Nunca vendió

    return np.mean(ganancias_descontadas), np.std(ganancias_descontadas) / np.sqrt(num_sims)

# Parámetros del mercado discretizado
m_estados = 20
x_inicial = 10        # Precio inicial del activo
K_costo = 5           # Costo fijo (Strike price)
beta_desc = 0.95      # Factor de descuento (impaciencia/costo de capital)
p_subida = 0.5        # Mercado neutral (martingala pura sin descuento)
num_simulaciones = 10000

umbrales_candidatos = np.arange(10, 21) # Probar vender en 10, 11, ..., 20
valores_esperados = []
errores_estandar = []

print("Simulando estrategias Monte Carlo... (esto tomará unos segundos)")
for i_star in umbrales_candidatos:
    media, error = simular_venta_umbral(i_star, x_inicial, K_costo, beta_desc, p_subida, m_estados, num_simulaciones)
    valores_esperados.append(media)
    errores_estandar.append(error)

valores_esperados = np.array(valores_esperados)
errores_estandar = np.array(errores_estandar)

# Encontrar el umbral óptimo empírico
idx_optimo = np.argmax(valores_esperados)
umbral_optimo = umbrales_candidatos[idx_optimo]
ganancia_maxima = valores_esperados[idx_optimo]

print("--- RESULTADOS EJERCICIO 4.12 ---")
print(f"Umbral Óptimo Encontrado: Vender al llegar a {umbral_optimo}")
print(f"Ganancia Descontada Máxima: {ganancia_maxima:.4f}")

# ----- GENERACIÓN DE LA GRÁFICA -----
fig, ax = plt.subplots(figsize=(10, 6))

ax.plot(umbrales_candidatos, valores_esperados, marker='o', color=colores_fes[0], lw=2.5, markersize=8, label='Ganancia Media Esperada')
ax.fill_between(umbrales_candidatos, valores_esperados - 1.96*errores_estandar, valores_esperados + 1.96*errores_estandar, color=colores_fes[0], alpha=0.2, label='Intervalo Confianza (95%)')

# Destacar el óptimo
ax.axvline(umbral_optimo, color=colores_fes[1], linestyle='--', lw=2.5, label=f'Umbral Óptimo ($i^* = {umbral_optimo}$)')
ax.plot(umbral_optimo, ganancia_maxima, marker='*', color=colores_fes[1], markersize=15)

ax.set_title('Optimización de la Política de Venta mediante Monte Carlo', fontsize=15, fontweight='bold')
ax.set_xlabel('Umbral de Venta ($i^*$)', fontsize=12)
ax.set_ylabel('Ganancia Descontada Esperada $\mathbb{E}[\\beta^{\\tau} (X_{\\tau} - K)]$', fontsize=12)
ax.set_xticks(umbrales_candidatos)
ax.legend(fontsize=11)

plt.tight_layout()
plt.savefig('fig4_12_pro.png', dpi=300)
plt.show()

import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

# Configuración de estilo profesional
sns.set_theme(style="whitegrid", context="notebook")
colores_fes = ['#2C4B78', '#B8862D', '#5A6B7C']

# Parámetros del proceso
lam = 5.0          # Intensidad de Poisson
T = 10.0           # Horizonte temporal
m_grid = 500       # Número de puntos en la malla
num_sims = 10000   # Número de trayectorias

t_grid = np.linspace(0, T, m_grid + 1)
dt = T / m_grid

# ==========================================
# EJERCICIO 5.11: Martingala Compensada
# ==========================================
print("Simulando trayectorias... esto puede tardar un momento.")
# a) Simular incrementos y trayectorias de N_t
incrementos = np.random.poisson(lam * dt, (num_sims, m_grid))
N_t = np.zeros((num_sims, m_grid + 1))
N_t[:, 1:] = np.cumsum(incrementos, axis=1)

# Construir la martingala compensada M_t = N_t - lambda * t
M_t = N_t - lam * t_grid

# b) Estimar E[M_t]
media_M = np.mean(M_t, axis=0)

# c) Estimar E[M_t^2] y comparar con lambda * t
segundo_momento_M = np.mean(M_t**2, axis=0)
var_teorica = lam * t_grid

# d) Variación cuadrática opcional vs Compensador (para 1 trayectoria representativa)
idx = 0  # Tomamos la primera trayectoria como ejemplo
VCO_single = N_t[idx, :]   # [M]_t = N_t
compensador = lam * t_grid # <M>_t = lambda * t

print("--- RESULTADOS EJERCICIO 5.11 ---")
print(f"Media empírica final E[M_T]: {media_M[-1]:.4f} (Debe ser ~ 0)")
print(f"Segundo momento empírico final E[M_T^2]: {segundo_momento_M[-1]:.4f}")
print(f"Segundo momento teórico (lam*T): {var_teorica[-1]:.4f}")

# ----- GENERACIÓN DE LA GRÁFICA -----
fig, axes = plt.subplots(1, 3, figsize=(18, 5))

# Panel 1: Trayectorias y Media de M_t
for i in range(15): # Mostrar 15 trayectorias de fondo
    axes[0].plot(t_grid, M_t[i, :], color=colores_fes[2], alpha=0.15)
axes[0].plot(t_grid, media_M, color=colores_fes[1], lw=3, label='Media Empírica $\mathbb{E}[M_t]$')
axes[0].axhline(0, color='red', linestyle='--', lw=2, label='Teórica (0)')
axes[0].set_title('Martingala Compensada ($M_t$)', fontsize=14, fontweight='bold')
axes[0].set_xlabel('Tiempo (t)')
axes[0].set_ylabel('$M_t = N_t - \lambda t$')
axes[0].legend()

# Panel 2: Isometría (Segundo Momento)
axes[1].plot(t_grid, segundo_momento_M, color=colores_fes[0], lw=3, label='Empírica $\mathbb{E}[M_t^2]$')
axes[1].plot(t_grid, var_teorica, color='red', linestyle='--', lw=2, label='Teórica ($\lambda t$)')
axes[1].set_title('Isometría de Itô Discreta', fontsize=14, fontweight='bold')
axes[1].set_xlabel('Tiempo (t)')
axes[1].set_ylabel('Segundo Momento')
axes[1].legend()

# Panel 3: Variación Cuadrática vs Compensador
axes[2].step(t_grid, VCO_single, where='post', color=colores_fes[0], lw=2, label='Var. Cuadrática $[M]_t = N_t$')
axes[2].plot(t_grid, compensador, color='red', linestyle='--', lw=2, label='Compensador $\langle M \\rangle_t = \lambda t$')
axes[2].set_title('Variación Cuadrática vs Compensador', fontsize=14, fontweight='bold')
axes[2].set_xlabel('Tiempo (t)')
axes[2].set_ylabel('Acumulación')
axes[2].legend()

plt.tight_layout()
plt.savefig('fig5_11_pro.png', dpi=300)
plt.show()

import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from scipy.stats import poisson

# Configuración de estilo profesional
sns.set_theme(style="whitegrid", context="notebook")
colores_fes = ['#2C4B78', '#B8862D', '#5A6B7C']

# Parámetros del experimento
lam = 2.0                 # Intensidad original bajo P
theta = np.log(1.5)       # Cambio de medida: lam_nueva = lam * e^theta = 3.0
lam_Q = lam * np.exp(theta)
T = 5.0                   # Horizonte temporal
num_sims = 100000         # Alta cantidad de simulaciones para estabilidad de pesos

# ==========================================
# EJERCICIO 5.12: Cambio de Medida (Girsanov)
# ==========================================

print("Simulando cambio de medida... ")

# a) Simular bajo la medida original P
N_T = np.random.poisson(lam * T, num_sims)

# Calcular los pesos de la martingala (Derivada de Radon-Nikodym)
Z_T = np.exp(theta * N_T - lam * T * (np.exp(theta) - 1))

# b) Estimar distribución bajo la medida inclinada Q (Muestreo por Importancia)
max_k = int(np.max(N_T)) + 15
k_vals = np.arange(max_k)

# Probabilidad empírica bajo P (Frecuencia normal)
prob_P_emp = np.bincount(N_T, minlength=max_k) / num_sims

# Probabilidad empírica bajo Q (Frecuencia PONDERADA por Z_T)
prob_Q_emp = np.bincount(N_T, weights=Z_T, minlength=max_k) / num_sims

# Probabilidad Teórica bajo Q
prob_Q_teo = poisson.pmf(k_vals, lam_Q * T)

# c) Estudio de la varianza del estimador (Z_t) para distintos T
T_vals = np.linspace(1, 15, 15)
var_Z = []
for t_ in T_vals:
    # Simulamos para cada t
    n_t = np.random.poisson(lam * t_, num_sims)
    z_t = np.exp(theta * n_t - lam * t_ * (np.exp(theta) - 1))
    var_Z.append(np.var(z_t))

print("--- RESULTADOS EJERCICIO 5.12 ---")
print(f"Intensidad original P: {lam} | Intensidad nueva Q: {lam_Q}")
print(f"Media esperada empírica bajo Q: {np.sum(k_vals * prob_Q_emp):.4f} (Teórica: {lam_Q * T})")

# ----- GENERACIÓN DE LA GRÁFICA -----
fig, (ax1, ax2) = plt.subplots(1, 2, figsize=(15, 6))

# Panel 1: Cambio de Medida (Distribuciones)
ax1.bar(k_vals - 0.2, prob_P_emp, width=0.4, color=colores_fes[2], alpha=0.6, label=f'Empírica $\mathbb{{P}}$ ($\lambda={lam}$)')
ax1.bar(k_vals + 0.2, prob_Q_emp, width=0.4, color=colores_fes[0], alpha=0.8, label='Ponderada $\mathbb{{Q}}^{(\\theta)}$ ($Z_T$-weighted)')
ax1.plot(k_vals, prob_Q_teo, 'ro-', lw=2, label=f'Teórica Poisson($\lambda e^{{\\theta}}={lam_Q}$)')

ax1.set_title('Reconstrucción de Medida (Muestreo por Importancia)', fontsize=14, fontweight='bold')
ax1.set_xlabel('Eventos en el tiempo $T$ ($N_T$)', fontsize=12)
ax1.set_ylabel('Probabilidad', fontsize=12)
ax1.set_xlim(0, 30)
ax1.legend()

# Panel 2: Explosión de la Varianza de Radon-Nikodym
ax2.plot(T_vals, var_Z, marker='s', color=colores_fes[1], lw=2.5, markersize=8)
ax2.set_yscale('log') # Escala logarítmica para ver el crecimiento exponencial
ax2.set_title('Degeneración del Estimador (Varianza de $Z_t$ vs Tiempo)', fontsize=14, fontweight='bold')
ax2.set_xlabel('Horizonte Temporal ($T$)', fontsize=12)
ax2.set_ylabel('Varianza de $Z_T$ (Escala Log)', fontsize=12)

# Rellenar zona de peligro
ax2.axhspan(1e2, max(var_Z)*2, color='red', alpha=0.1, label='Alta Varianza (Degeneración de Pesos)')
ax2.legend()

plt.tight_layout()
plt.savefig('fig5_12_pro.png', dpi=300)
plt.show()